wt88047: init: depend on libselinux_defaults
system/core/init/util.h:29:10: fatal error: 'selinux/label.h' file not found

Change-Id: Id27b13647465e03a9131e385876e0cf655baccca
Signed-off-by: RahifM <faizel326@gmail.com>